FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://install.python-poetry.org | python3 - \
    && ln -s /root/.local/bin/poetry /usr/local/bin/poetry

ENV PATH="/root/.local/bin:$PATH"

WORKDIR /app

COPY pyproject.toml /app/
    
RUN poetry install --no-root
    
COPY . /app

EXPOSE 8501

CMD ["poetry", "run", "streamlit", "run", "/app/app.py"]
